"""Fund master analysis and cross-dataset validation.

Day 1 Capstone - Mutual Fund Analytics Platform

Implements:
- TASK 3: FUND MASTER ANALYSIS
    - Count unique fund houses
    - Count unique categories
    - Count unique subcategories
    - Count risk grades
    - Output: reports/fund_master_summary.txt

- TASK 4: DATA VALIDATION
    - Validate every scheme code in fund_master exists in nav_history
    - Output: reports/validation_report.txt

Usage:
    python scripts/data_quality_check.py

Optional arguments:
    --fund-master path/to/fund_master.csv
    --raw-dir data/raw
    --reports-dir reports

Notes:
- The script tries to auto-discover a fund master CSV if not provided.
- NAV history is expected under data/raw/nav_history/ as generated by live_nav_fetch.py.
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set

import pandas as pd


LOGGER_NAME = "mutual_fund_analytics.data_quality_check"


def utc_now() -> datetime:
    """Return timezone-aware UTC 'now'."""
    return datetime.now(timezone.utc)


@dataclass(frozen=True)
class FundMasterColumns:
    scheme_code: str
    fund_house: Optional[str]
    category: Optional[str]
    subcategory: Optional[str]
    risk_grade: Optional[str]


def configure_logging(log_level: str) -> logging.Logger:
    logger = logging.getLogger(LOGGER_NAME)
    logger.setLevel(getattr(logging, log_level.upper(), logging.INFO))

    if logger.handlers:
        return logger

    formatter = logging.Formatter(
        fmt="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(formatter)
    logger.addHandler(handler)

    logger.propagate = False
    return logger


def safe_read_csv(
    path: Path,
    *,
    usecols: Optional[Sequence[str]] = None,
    nrows: Optional[int] = None,
) -> pd.DataFrame:
    kwargs: Dict[str, object] = {"low_memory": False}
    if usecols is not None:
        kwargs["usecols"] = list(usecols)
    if nrows is not None:
        kwargs["nrows"] = int(nrows)

    try:
        return pd.read_csv(path, encoding="utf-8", **kwargs)
    except UnicodeDecodeError:
        return pd.read_csv(path, encoding="latin-1", **kwargs)


def build_fund_master_from_nav_history(nav_history_dir: Path, logger: logging.Logger) -> pd.DataFrame:
    """Build a minimal fund master table from nav_history CSV metadata.

    This is a pragmatic fallback for Day 1 when a separate fund master CSV
    hasn't been provided yet.
    """
    if not nav_history_dir.exists():
        logger.warning("NAV history directory does not exist: %s", nav_history_dir.as_posix())
        return pd.DataFrame(columns=["scheme_code", "scheme_name", "fund_house", "scheme_type", "scheme_category"])

    rows: List[Dict[str, str]] = []
    files = sorted(nav_history_dir.glob("*.csv"))
    if not files:
        logger.warning("No NAV history CSVs found in %s", nav_history_dir.as_posix())
        return pd.DataFrame(columns=["scheme_code", "scheme_name", "fund_house", "scheme_type", "scheme_category"])

    for path in files:
        try:
            df = safe_read_csv(path)
            if df.empty:
                continue
            first = df.iloc[0]
            rows.append(
                {
                    "scheme_code": str(first.get("scheme_code", path.stem)).strip(),
                    "scheme_name": str(first.get("scheme_name", "")).strip(),
                    "fund_house": str(first.get("fund_house", "")).strip(),
                    "scheme_type": str(first.get("scheme_type", "")).strip(),
                    "scheme_category": str(first.get("scheme_category", "")).strip(),
                }
            )
        except (OSError, ValueError, pd.errors.EmptyDataError, pd.errors.ParserError):
            logger.exception("Failed reading NAV history file for fund master fallback: %s", path.as_posix())

    if not rows:
        return pd.DataFrame(columns=["scheme_code", "scheme_name", "fund_house", "scheme_type", "scheme_category"])

    fund_master = pd.DataFrame(rows).drop_duplicates(subset=["scheme_code"])
    return fund_master


def normalize_colname(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.strip().lower()).strip("_")


def build_column_index(columns: Iterable[str]) -> Dict[str, str]:
    """Map normalized column name -> original column name."""
    index: Dict[str, str] = {}
    for col in columns:
        norm = normalize_colname(col)
        # Prefer first occurrence if duplicates exist.
        index.setdefault(norm, col)
    return index


def pick_first(index: Dict[str, str], candidates: Sequence[str]) -> Optional[str]:
    for cand in candidates:
        if cand in index:
            return index[cand]
    return None


def detect_fund_master_columns(df: pd.DataFrame) -> FundMasterColumns:
    """Detect key columns in a fund master table using heuristics."""
    idx = build_column_index(df.columns)

    # Scheme code is required.
    scheme_code = pick_first(
        idx,
        [
            "scheme_code",
            "amfi_code",
            "amficode",
            "schemecode",
            "code",
            "scheme",
            "scheme_id",
            "schemeid",
        ],
    )
    if scheme_code is None:
        # Try fuzzy match for anything containing both scheme and code.
        for norm, original in idx.items():
            if "scheme" in norm and "code" in norm:
                scheme_code = original
                break

    if scheme_code is None:
        raise ValueError(
            "Unable to detect scheme code column in fund master CSV. "
            "Expected a column like 'scheme_code' or similar."
        )

    fund_house = pick_first(idx, ["fund_house", "fundhouse", "amc", "asset_management_company"])
    category = pick_first(idx, ["scheme_category", "category", "fund_category", "scheme_cat"])
    subcategory = pick_first(idx, ["scheme_sub_category", "subcategory", "sub_category", "subcat"])
    risk_grade = pick_first(
        idx,
        [
            "risk_grade",
            "risk_category",
            "risk",
            "riskometer",
            "risk_level",
            "risk_grade_text",
        ],
    )

    return FundMasterColumns(
        scheme_code=scheme_code,
        fund_house=fund_house,
        category=category,
        subcategory=subcategory,
        risk_grade=risk_grade,
    )


def autodiscover_fund_master(raw_dir: Path) -> Optional[Path]:
    """Try to locate a likely fund master CSV in data/raw."""
    candidates: List[Path] = []
    for p in raw_dir.glob("*.csv"):
        name = p.name.lower()
        if "fund" in name and "master" in name:
            candidates.append(p)

    if candidates:
        return sorted(candidates)[0]

    # Common capstone datasets often live under project_root/dataset.
    project_root = Path(__file__).resolve().parents[1]
    dataset_dir = project_root / "dataset"
    preferred = dataset_dir / "01_fund_master.csv"
    if preferred.exists():
        return preferred

    if dataset_dir.exists():
        dataset_candidates = [p for p in dataset_dir.glob("*.csv") if "fund" in p.name.lower() and "master" in p.name.lower()]
        if dataset_candidates:
            return sorted(dataset_candidates)[0]

    # Fallback: any top-level CSV (exclude known nav outputs)
    top_level = [p for p in raw_dir.glob("*.csv") if p.name.lower() not in {"live_nav_hdfc_top100.csv"}]
    return sorted(top_level)[0] if top_level else None


def analyze_fund_master(df: pd.DataFrame, cols: FundMasterColumns) -> Dict[str, int]:
    """Compute requested unique counts."""
    out: Dict[str, int] = {}

    if cols.fund_house and cols.fund_house in df.columns:
        out["unique_fund_houses"] = int(df[cols.fund_house].dropna().astype(str).nunique())
    else:
        out["unique_fund_houses"] = 0

    if cols.category and cols.category in df.columns:
        out["unique_categories"] = int(df[cols.category].dropna().astype(str).nunique())
    else:
        out["unique_categories"] = 0

    if cols.subcategory and cols.subcategory in df.columns:
        out["unique_subcategories"] = int(df[cols.subcategory].dropna().astype(str).nunique())
    else:
        out["unique_subcategories"] = 0

    if cols.risk_grade and cols.risk_grade in df.columns:
        out["unique_risk_grades"] = int(df[cols.risk_grade].dropna().astype(str).nunique())
    else:
        out["unique_risk_grades"] = 0

    return out


def write_fund_master_summary(
    output_path: Path,
    fund_master_source: str,
    cols: FundMasterColumns,
    counts: Dict[str, int],
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8") as f:
        f.write("Mutual Fund Analytics Platform - Fund Master Summary\n")
        f.write(f"Generated at: {utc_now().isoformat(timespec='seconds')}\n")
        f.write(f"Fund master source: {fund_master_source}\n")
        f.write("\n")
        f.write("Detected Columns\n")
        f.write("----------------\n")
        f.write(f"scheme_code: {cols.scheme_code}\n")
        f.write(f"fund_house: {cols.fund_house or 'NOT FOUND'}\n")
        f.write(f"category: {cols.category or 'NOT FOUND'}\n")
        f.write(f"subcategory: {cols.subcategory or 'NOT FOUND'}\n")
        f.write(f"risk_grade: {cols.risk_grade or 'NOT FOUND'}\n")
        f.write("\n")
        f.write("Unique Counts\n")
        f.write("-------------\n")
        f.write(f"Unique Fund Houses: {counts['unique_fund_houses']}\n")
        f.write(f"Unique Categories: {counts['unique_categories']}\n")
        f.write(f"Unique Subcategories: {counts['unique_subcategories']}\n")
        f.write(f"Unique Risk Grades: {counts['unique_risk_grades']}\n")


def detect_code_column(df: pd.DataFrame) -> str:
    idx = build_column_index(df.columns)
    code_col = pick_first(
        idx,
        [
            "scheme_code",
            "amfi_code",
            "amficode",
            "schemecode",
            "code",
            "scheme",
            "scheme_id",
            "schemeid",
        ],
    )
    if code_col is None:
        for norm, original in idx.items():
            if "amfi" in norm and "code" in norm:
                return original
            if "scheme" in norm and "code" in norm:
                return original
        raise ValueError("Unable to detect scheme/amfi code column")
    return code_col


def list_nav_history_scheme_codes(nav_history: Path, logger: logging.Logger) -> Set[str]:
    """List scheme codes present in NAV history.

    Supports:
    - Directory of per-scheme CSVs (data/raw/nav_history/*.csv)
    - Single NAV history CSV (e.g., dataset/02_nav_history.csv)
    """
    if not nav_history.exists():
        return set()

    if nav_history.is_dir():
        codes: Set[str] = set()
        for p in nav_history.glob("*.csv"):
            codes.add(p.stem.strip())
        return codes

    if nav_history.is_file():
        try:
            head = safe_read_csv(nav_history, nrows=5)
            code_col = detect_code_column(head)
            codes_df = safe_read_csv(nav_history, usecols=[code_col])
            return extract_fund_master_scheme_codes(codes_df, code_col)
        except (OSError, ValueError, pd.errors.EmptyDataError, pd.errors.ParserError):
            logger.exception("Failed extracting scheme codes from NAV history CSV: %s", nav_history.as_posix())
            return set()

    return set()


def extract_fund_master_scheme_codes(df: pd.DataFrame, scheme_code_col: str) -> Set[str]:
    codes = (
        df[scheme_code_col]
        .dropna()
        .astype(str)
        .str.strip()
        .replace({"": pd.NA})
        .dropna()
        .tolist()
    )
    return set(codes)


def write_validation_report(
    output_path: Path,
    total_codes: int,
    matched: Set[str],
    missing: Set[str],
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    validation_pct = (len(matched) / total_codes * 100.0) if total_codes else 0.0

    with output_path.open("w", encoding="utf-8") as f:
        f.write("Mutual Fund Analytics Platform - Validation Report\n")
        f.write(f"Generated at: {utc_now().isoformat(timespec='seconds')}\n")
        f.write("\n")
        f.write(f"Total Scheme Codes in Fund Master: {total_codes}\n")
        f.write(f"Matched Scheme Codes in NAV History: {len(matched)}\n")
        f.write(f"Missing Scheme Codes (not in NAV history): {len(missing)}\n")
        f.write(f"Validation Percentage: {validation_pct:.2f}%\n")
        f.write("\n")

        f.write("Missing Scheme Codes\n")
        f.write("--------------------\n")
        for code in sorted(missing):
            f.write(f"{code}\n")
        f.write("\n")

        f.write("Matched Scheme Codes\n")
        f.write("--------------------\n")
        for code in sorted(matched):
            f.write(f"{code}\n")


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fund master analysis and validation")
    parser.add_argument(
        "--raw-dir",
        type=Path,
        default=Path("data") / "raw",
        help="Raw data directory (default: data/raw)",
    )
    parser.add_argument(
        "--reports-dir",
        type=Path,
        default=Path("reports"),
        help="Reports directory (default: reports)",
    )
    parser.add_argument(
        "--fund-master",
        type=Path,
        default=None,
        help="Explicit fund master CSV path (optional)",
    )
    parser.add_argument(
        "--nav-history",
        type=Path,
        default=None,
        help=(
            "NAV history source (optional). Either a directory of per-scheme CSVs "
            "(e.g., data/raw/nav_history) or a single CSV (e.g., dataset/02_nav_history.csv). "
            "Defaults to <raw-dir>/nav_history."
        ),
    )
    parser.add_argument(
        "--log-level",
        type=str,
        default="INFO",
        help="Logging level (DEBUG, INFO, WARNING, ERROR)",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    logger = configure_logging(args.log_level)

    raw_dir: Path = args.raw_dir
    reports_dir: Path = args.reports_dir

    nav_history_source: Path = args.nav_history if args.nav_history is not None else (raw_dir / "nav_history")

    fund_master_path: Optional[Path] = args.fund_master
    if fund_master_path is None:
        fund_master_path = autodiscover_fund_master(raw_dir)

    fund_master_source: str
    if fund_master_path is not None and fund_master_path.exists():
        logger.info("Using fund master: %s", fund_master_path.as_posix())
        fund_master_source = fund_master_path.as_posix()
        try:
            fund_df = safe_read_csv(fund_master_path)
        except (OSError, ValueError, pd.errors.EmptyDataError, pd.errors.ParserError):
            logger.exception("Failed reading fund master CSV")
            return 3
    else:
        logger.warning(
            "Fund master CSV not found. Falling back to building a minimal fund master from %s",
            nav_history_source.as_posix(),
        )
        fund_master_source = f"NAV history metadata ({nav_history_source.as_posix()})"
        fund_df = build_fund_master_from_nav_history(raw_dir / "nav_history", logger)

    try:
        cols = detect_fund_master_columns(fund_df)
    except ValueError:
        logger.exception("Failed detecting required columns in fund master")
        return 4

    counts = analyze_fund_master(fund_df, cols)

    summary_path = reports_dir / "fund_master_summary.txt"
    try:
        write_fund_master_summary(summary_path, fund_master_source, cols, counts)
        logger.info("Wrote fund master summary: %s", summary_path.as_posix())
    except OSError:
        logger.exception("Failed writing fund master summary")
        return 5

    nav_codes = list_nav_history_scheme_codes(nav_history_source, logger)
    logger.info("NAV history codes discovered: %s", len(nav_codes))

    fund_codes = extract_fund_master_scheme_codes(fund_df, cols.scheme_code)

    matched = fund_codes.intersection(nav_codes)
    missing = fund_codes.difference(nav_codes)

    validation_path = reports_dir / "validation_report.txt"
    try:
        write_validation_report(validation_path, len(fund_codes), matched, missing)
        logger.info("Wrote validation report: %s", validation_path.as_posix())
    except OSError:
        logger.exception("Failed writing validation report")
        return 6

    logger.info("Completed quality checks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
